### ISSUE TITLE
Installation script doesn't install comparison operators.

### ISSUE THREAD

**Issue by PixelOcelot** [decibel/variant#4] opened 2015-05-06 08:10 UTC
Issue is found for [9b4ca82](https://github.com/decibel/variant/commit/9b4ca82f0560953fd9ce55426c874c7ca601ecff) commit.
I'm using PostgreSQL 9.4 x86. Extension built with msvc.

For some reason, after creating extension, I can't use comparison  operators. They're not found.
Though, they're created in installation script. But if I copy this part of script and manually create them, they are found.
Maybe because different schema used(not variant) and operators are not shared?

**Comment by decibel** [comment] 2015-05-06 16:20
I think the problem is that the extension specifies that it goes in a specific schema, which sets search_path, putting all the operators there.

I'm not sure what a good solution is. IIRC there were some problems with not specifying the schema to install to in the .control file, but you could try removing the schema = line from variant.control before installing.

BTW, you can still use the original operators; you would just need to schema specify them, ie: a variant.< b.

**Comment by decibel** [comment] 2015-05-06 16:45
Hmm... I see you can't actually use variant.<. :(

**Comment by PixelOcelot** [comment] 2015-05-06 16:54
Yeah, I tried it already :) But I think it's not that big problem. Easy workaround: create them manually. But for future redistribution that issue should be considered.
Have you tried to switch back to current schema in installation script(it is variant--version.sql not version.control, isn't it?) for creating operators? 
However this solution still isn't convenient for people who use multiple schemas :(

**Comment by decibel** [comment] 2015-07-15 18:50
BTW, I realize now that the way to schema-qualify an operator is with OPERATOR(), ie OPERATOR( variant.< ).

As shown in Issue #5, getting better variant operators is going to be very difficult, so I'm going to close this issue and keep #5 open.

**Closed by decibel** 2015-07-15 18:50 UTC
